# Generated by Django 5.0.4 on 2024-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=20)),
                ('conv_id', models.IntegerField(default=1, unique=True)),
                ('conv_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField(default=1, unique=True)),
                ('msg', models.TextField()),
                ('conv_id', models.IntegerField()),
                ('msg_type', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
