# Generated by Django 5.0.4 on 2024-05-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(default=1, unique=True)),
                ('doc_path', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=20)),
            ],
        ),
    ]
