# Generated by Django 5.0.4 on 2024-05-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0003_enterprisedocuments_userdocuments_delete_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conv_id',
        ),
        migrations.RemoveField(
            model_name='enterprisedocuments',
            name='edoc_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msg_id',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='udoc_id',
        ),
    ]
