# Generated by Django 5.0.4 on 2024-05-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0005_alter_users_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='email_id',
            field=models.CharField(max_length=50),
        ),
    ]
