# Generated by Django 5.0.4 on 2024-05-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0006_alter_conversation_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
