# Generated by Django 5.0.4 on 2024-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0008_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(max_length=2000),
        ),
    ]
