# Generated by Django 5.0.4 on 2024-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0009_alter_message_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(),
        ),
    ]
