# Generated by Django 5.0.4 on 2024-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0010_alter_message_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
