# Generated by Django 5.0.4 on 2024-05-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0011_message_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
