# Generated by Django 5.0.4 on 2024-05-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0012_conversation_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocuments',
            name='email_id',
            field=models.CharField(max_length=50),
        ),
    ]
