# Generated by Django 5.0.4 on 2024-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0013_alter_userdocuments_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.TextField()),
                ('enterprise_word', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RephrasedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.TextField()),
                ('rephrased_query', models.TextField()),
            ],
        ),
    ]
