# Generated by Django 5.0.4 on 2024-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0014_enterprisedictionary_rephrasedquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_from',
            field=models.TextField(default='not applicable'),
        ),
    ]
