# Generated by Django 5.0.4 on 2024-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0016_systemprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conv_name',
            field=models.CharField(max_length=50),
        ),
    ]
