# Generated by Django 5.0.4 on 2024-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0017_alter_conversation_conv_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
