# Generated by Django 5.0.4 on 2024-06-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0018_llmtemperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
