# Generated by Django 5.0.4 on 2024-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0019_conversation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('endpoint', models.TextField()),
                ('key', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
