# Generated by Django 5.0.4 on 2024-06-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0020_llm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hate', models.IntegerField()),
                ('sexual', models.IntegerField()),
                ('violence', models.IntegerField()),
            ],
        ),
    ]
