# Generated by Django 5.0.4 on 2024-06-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0021_contentfilters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentFilters',
        ),
    ]
